/* IANA DHCPv4 option name table. See cf_dhcpv4_optnames.h. */

#include "cf_dhcpv4_optnames.h"

const char *cf_dhcpv4_option_name(uint32_t code)
{
    switch (code) {
    case 0:   return "Pad";
    case 1:   return "Subnet Mask";
    case 2:   return "Time Offset";
    case 3:   return "Router";
    case 4:   return "Time Server";
    case 5:   return "Name Server";
    case 6:   return "Domain Server";
    case 7:   return "Log Server";
    case 8:   return "Quotes Server";
    case 9:   return "LPR Server";
    case 10:  return "Impress Server";
    case 11:  return "RLP Server";
    case 12:  return "Hostname";
    case 13:  return "Boot File Size";
    case 14:  return "Merit Dump File";
    case 15:  return "Domain Name";
    case 16:  return "Swap Server";
    case 17:  return "Root Path";
    case 18:  return "Extension File";
    case 19:  return "Forward On/Off";
    case 20:  return "SrcRte On/Off";
    case 21:  return "Policy Filter";
    case 22:  return "Max DG Assembly";
    case 23:  return "Default IP TTL";
    case 24:  return "MTU Timeout";
    case 25:  return "MTU Plateau";
    case 26:  return "MTU Interface";
    case 27:  return "MTU Subnet";
    case 28:  return "Broadcast Address";
    case 29:  return "Mask Discovery";
    case 30:  return "Mask Supplier";
    case 31:  return "Router Discovery";
    case 32:  return "Router Request";
    case 33:  return "Static Route";
    case 34:  return "Trailers";
    case 35:  return "ARP Timeout";
    case 36:  return "Ethernet";
    case 37:  return "Default TCP TTL";
    case 38:  return "Keepalive Time";
    case 39:  return "Keepalive Data";
    case 40:  return "NIS Domain";
    case 41:  return "NIS Servers";
    case 42:  return "NTP Servers";
    case 43:  return "Vendor Specific Information";
    case 44:  return "NETBIOS Name Srv";
    case 45:  return "NETBIOS Dist Srv";
    case 46:  return "NETBIOS Node Type";
    case 47:  return "NETBIOS Scope";
    case 48:  return "X Window Font";
    case 49:  return "X Window Manager";
    case 50:  return "Requested IP Address";
    case 51:  return "IP Address Lease Time";
    case 52:  return "Overload";
    case 53:  return "DHCP Message Type";
    case 54:  return "DHCP Server Identifier";
    case 55:  return "Parameter Request List";
    case 56:  return "Message";
    case 57:  return "DHCP Max Message Size";
    case 58:  return "Renewal Time Value";
    case 59:  return "Rebinding Time Value";
    case 60:  return "Class Identifier";
    case 61:  return "Client Identifier";
    case 64:  return "NIS+ Domain";
    case 65:  return "NIS+ Server";
    case 66:  return "TFTP Server Name";
    case 67:  return "Bootfile Name";
    case 68:  return "Mobile IP Home Agent";
    case 69:  return "SMTP Server";
    case 70:  return "POP3 Server";
    case 71:  return "NNTP Server";
    case 72:  return "WWW Server";
    case 73:  return "Finger Server";
    case 74:  return "IRC Server";
    case 75:  return "StreetTalk Server";
    case 76:  return "STDA Server";
    case 77:  return "User Class";
    case 78:  return "Directory Agent";
    case 79:  return "Service Scope";
    case 80:  return "Rapid Commit";
    case 81:  return "FQDN, Fully Qualified Domain Name";
    case 82:  return "Relay Agent Information";
    case 83:  return "iSNS";
    case 85:  return "NDS Servers";
    case 86:  return "NDS Tree Name";
    case 87:  return "NDS Context";
    case 88:  return "BCMCS Controller Domain Name list";
    case 89:  return "BCMCS Controller IPv4 address list";
    case 90:  return "Authentication";
    case 91:  return "client-last-transaction-time";
    case 92:  return "associated-ip";
    case 93:  return "Client System Architecture Type";
    case 94:  return "Client Network Interface Identifier";
    case 95:  return "LDAP";
    case 97:  return "UUID/GUID-based Client Identifier";
    case 98:  return "User-Auth";
    case 99:  return "GEOCONF_CIVIC";
    case 100: return "PCode";
    case 101: return "TCode";
    case 112: return "Netinfo Address";
    case 113: return "Netinfo Tag";
    case 114: return "URL";
    case 116: return "Auto Config";
    case 117: return "Name Service Search";
    case 118: return "Subnet Selection Option";
    case 119: return "Domain Search";
    case 120: return "SIP Servers DHCP Option";
    case 121: return "Classless Static Route";
    case 122: return "CCC, CableLabs Client Configuration";
    case 123: return "GeoConf";
    case 124: return "V-I Vendor Class";
    case 125: return "V-I Vendor-Specific Information";
    case 136: return "PANA Agent";
    case 137: return "V4 Lost";
    case 138: return "CAPWAP Access Controller addresses";
    case 141: return "SIP UA Configuration Service Domains";
    case 145: return "Forcerenew Nonce Capable";
    case 146: return "RDNSS Selection";
    case 150: return "TFTP Server Address";
    case 159: return "V4 Portparams";
    case 175: return "Etherboot (Tentatively Assigned)";
    case 208: return "PXELINUX Magic (deprecated)";
    case 209: return "Configuration File";
    case 210: return "Path Prefix";
    case 211: return "Reboot Time";
    case 212: return "OPTION_6RD";
    case 213: return "OPTION_V4_ACCESS_DOMAIN";
    case 220: return "Subnet Allocation Option";
    case 221: return "Virtual Subnet Selection";
    case 249: return "Microsoft Classless Static Route";
    case 252: return "Proxy autodiscovery (WPAD)";
    case 255: return "End";
    default:  return "";
    }
}
