#!/usr/bin/env bash
# scripts/generate-protobuf.sh
#
# WP-02: regenerates all protobuf bindings for the CloudFlow schema under
# proto/cloudflow/v1/*.proto. Generated code is committed (Decision D2 in
# docs/architecture.md) so builds and CI never need protoc. Run this
# script (via `make proto`) whenever a .proto file changes, and commit the
# resulting diff.
#
#   C:      libs/cloudflow-codec/gen/cloudflow/v1/*.pb-c.{c,h}   (protobuf-c)
#   Python: sinks/cloudflow-sink-splunk/src/cloudflow_pb/cloudflow/v1/*_pb2.py
#
# Idempotent: running it twice in a row produces no further changes to the
# working tree (WP-02 acceptance criterion). Stale output is removed before
# regenerating so files deleted/renamed upstream do not linger.
set -euo pipefail

# Resolve the repo root regardless of the caller's cwd, so this script can be
# invoked as ./scripts/generate-protobuf.sh, via `make proto` from anywhere
# SUBDIRS invoke make from, etc.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
ROOT_DIR="$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)"
cd "${ROOT_DIR}"

PROTO_DIR="proto/cloudflow/v1"
C_OUT_DIR="libs/cloudflow-codec/gen"
PY_OUT_ROOT="sinks/cloudflow-sink-splunk/src/cloudflow_pb"
PY_OUT_DIR="${PY_OUT_ROOT}/cloudflow/v1"

fail() {
    echo "generate-protobuf.sh: error: $*" >&2
    exit 1
}

command -v protoc >/dev/null 2>&1 \
    || fail "protoc not found on PATH. Install protobuf-compiler (see README.md)."
command -v protoc-gen-c >/dev/null 2>&1 \
    || fail "protoc-gen-c not found on PATH. Install protobuf-c-compiler (see README.md)."

# Echo the exact tool versions used for this generation run.
PROTOC_VERSION="$(protoc --version)"
# protoc-gen-c has no --version flag; report the package version via dpkg if
# available, otherwise just note that the binary was found.
if command -v dpkg-query >/dev/null 2>&1 && dpkg-query -W -f='${Version}' protobuf-c-compiler >/dev/null 2>&1; then
    PROTOC_GEN_C_VERSION="protobuf-c-compiler $(dpkg-query -W -f='${Version}' protobuf-c-compiler)"
else
    PROTOC_GEN_C_VERSION="$(command -v protoc-gen-c) (version unknown: protoc-gen-c has no --version flag)"
fi
echo "generate-protobuf.sh: using ${PROTOC_VERSION}"
echo "generate-protobuf.sh: using protoc-gen-c: ${PROTOC_GEN_C_VERSION}"

PROTO_FILES=("${PROTO_DIR}"/*.proto)
[ -e "${PROTO_FILES[0]}" ] || fail "no .proto files found under ${PROTO_DIR}"

# --- C bindings (protobuf-c) -----------------------------------------------
# Clean stale generated output first so removed/renamed .proto files don't
# leave orphaned generated sources behind (idempotence / correctness).
rm -rf "${C_OUT_DIR}"
mkdir -p "${C_OUT_DIR}"

protoc \
    --c_out="${C_OUT_DIR}" \
    --proto_path=proto \
    "${PROTO_FILES[@]}"

cat > "${C_OUT_DIR}/README.md" <<'EOF'
# GENERATED -- do not edit

Everything under this directory is generated by `scripts/generate-protobuf.sh`
(invoked via `make proto`) from the schema in `proto/cloudflow/v1/*.proto`.

Do not hand-edit any file here. To regenerate after changing the .proto
files, run `make proto` from the repo root and commit the resulting diff.

Layout: `cloudflow/v1/{common,envelope,dhcp}.pb-c.{c,h}`, produced by
`protoc --c_out` with the `protoc-gen-c` plugin (protobuf-c).
EOF

# --- Python bindings (protobuf) ---------------------------------------------
# Clean the whole generated package root (not just cloudflow/v1/) so stale
# README/__init__.py files or removed proto packages don't linger.
rm -rf "${PY_OUT_ROOT}"
mkdir -p "${PY_OUT_DIR}"

protoc \
    --python_out="${PY_OUT_ROOT}" \
    --proto_path=proto \
    "${PROTO_FILES[@]}"

# protoc's --python_out lays files out at <out>/cloudflow/v1/*_pb2.py to
# mirror the proto package path (matching --proto_path=proto) but does not
# create __init__.py files. Add them so cloudflow/ and cloudflow/v1/ are
# importable packages.
#
# Import mechanics: protoc generates cross-file imports between the pb2
# modules as absolute imports relative to --proto_path, e.g.
# envelope_pb2.py contains `from cloudflow.v1 import common_pb2`. For those
# imports to resolve, the directory that directly *contains* the
# `cloudflow/` package -- i.e. this directory, `cloudflow_pb/` -- must be on
# PYTHONPATH/sys.path (not its parent). `cloudflow_pb` is just the on-disk
# container we generate into; it is not itself part of the import path.
cat > "${PY_OUT_ROOT}/README.md" <<'EOF'
# GENERATED -- do not edit

Everything under this directory (except this README) is generated by
`scripts/generate-protobuf.sh` (invoked via `make proto`) from the schema in
`proto/cloudflow/v1/*.proto`.

Do not hand-edit any file here. To regenerate after changing the .proto
files, run `make proto` from the repo root and commit the resulting diff.

Import path: protoc generates cross-file imports between the *_pb2.py
modules as absolute imports relative to --proto_path (e.g.
envelope_pb2.py does `from cloudflow.v1 import common_pb2`). For those
imports to resolve, put *this* directory
(`sinks/cloudflow-sink-splunk/src/cloudflow_pb`, the one directly
containing `cloudflow/`) on `PYTHONPATH` -- not its parent -- then:

    from cloudflow.v1 import envelope_pb2, dhcp_pb2
    from cloudflow.v1.envelope_pb2 import CloudFlowEvent

tests/unit/Makefile does this via
`PYTHONPATH=sinks/cloudflow-sink-splunk/src/cloudflow_pb` when running
`tests/unit/codec_roundtrip.py`.
EOF

# Only cloudflow/ and cloudflow/v1/ need to be packages -- cloudflow_pb/
# itself is the directory added to PYTHONPATH, not a package on the import
# path (see the README generated above).
: > "${PY_OUT_ROOT}/cloudflow/__init__.py"
: > "${PY_OUT_DIR}/__init__.py"

echo "generate-protobuf.sh: done."
echo "generate-protobuf.sh: C output:      ${C_OUT_DIR}/cloudflow/v1/"
echo "generate-protobuf.sh: Python output: ${PY_OUT_DIR}/"
